name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH keys for deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy to your server using SSH
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ruben5@192.168.1.100 << 'EOF'
          cd /home2/ruben5/eventtrackit.com
          git pull origin main  # Pull the latest changes
          # Add additional commands here if needed, e.g. restarting services
          sudo systemctl restart apache2  # Restart Apache
        EOF
